name: CI

on:
  push:
    branches: main
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
      - run: |
          # install hyperfine
          sudo apt-get install -y hyperfine
          # build
          ./mill server.assembly
          ./mill client.jvm.assembly
          ./mill client.native.nativeLink
          # start the server in background
          java -jar ./out/server/assembly.dest/out.jar &
          # try JVM version
          java -jar ./out/client/jvm/assembly.dest/out.jar -c version
          java -jar ./out/client/jvm/assembly.dest/out.jar -c noop
          java -jar ./out/client/jvm/assembly.dest/out.jar -c subprocess
          java -jar ./out/client/jvm/assembly.dest/out.jar -c interactiveSubprocess
          java -jar ./out/client/jvm/assembly.dest/out.jar -c task1
          java -jar ./out/client/jvm/assembly.dest/out.jar -c task2
          java -jar ./out/client/jvm/assembly.dest/out.jar -c shutdown
          # try native version
          chmod +x ./out/client/native/nativeLink.dest/out.exe
          ./out/client/native/nativeLink.dest/out.exe -c version
          ./out/client/native/nativeLink.dest/out.exe -c noop
          ./out/client/native/nativeLink.dest/out.exe -c subprocess
          ./out/client/native/nativeLink.dest/out.exe -c interactiveSubprocess
          ./out/client/native/nativeLink.dest/out.exe -c task1
          ./out/client/native/nativeLink.dest/out.exe -c task2
          ./out/client/native/nativeLink.dest/out.exe -c shutdown
          # mini bench
          hyperfine --show-output "java -jar ./out/client/jvm/assembly.dest/out.jar -c noop"
          hyperfine --show-output "./out/client/native/nativeLink.dest/out.exe -c noop"
